%run

In [3]:
import numpy as np

In [3]:
np.__version__

'1.14.0'

In [5]:
np.full((3, 5), 666, dtype=float)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

In [5]:
a = np.array([1,3,5])
b = np.array([2,4,6])

In [7]:
c= np.concatenate([a, b])

In [8]:
c

array([1, 3, 5, 2, 4, 6])

In [9]:
A = np.array([[1,2,1],
             [2,3,4]])

In [10]:
np.concatenate([A, A])

array([[1, 2, 1],
       [2, 3, 4],
       [1, 2, 1],
       [2, 3, 4]])

In [12]:
np.concatenate([A,A], axis=1)

array([[1, 2, 1, 1, 2, 1],
       [2, 3, 4, 2, 3, 4]])

In [17]:
z=np.array([6,6,6])

### 一维矩阵如何concate进入二维矩阵

In [16]:
np.concatenate([A, z.reshape(1,-1)])

array([[1, 2, 1],
       [2, 3, 4],
       [6, 6, 6]])

### 分割操作

In [20]:
x = np.arange(0, 9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
x1, x2, x3, x4 = np.split(x, [3, 5, 7])
x1, x2, x3, x4

(array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8]))

#### 二维数组分割

In [27]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

##### 垂直分割

In [31]:
upper, lower = np.vsplit(A, [2])
upper, lower

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

##### 水平分割

In [34]:
left, right = np.hsplit(A, [2])
left, right

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))